### PR TITLE
Use the correct CLI option to enable TDZ in Hermes

### LINKED ISSUE #125: hermes command line arguments are incorrect
https://github.com/bterlson/eshost/blob/d1809998d823383a38ed022c0cda4245bd02c61b/lib/agents/hermes.js#L35 uses `-fenable-tdz`, which was renamed to `-Xenable-tdz` as of hermes v0.10.0: https://github.com/facebook/hermes/commit/f811a0e75f19ab0da7dcf969a61db894fbb3cc35

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #125

### CODE REVIEW

**Review by leotm — APPROVED** [review]
nice this worked perfectly earlier when eshost was running hermes cli 0.12.0 (HBC bytecode ver: 89) bin (from esvu/jsvu), i tested locally

```console
➜  npm list -g
/Users/leo/.nvm/versions/node/v22.13.1/lib
├── corepack@0.30.0
├── eshost-cli@9.0.0
├── esvu@1.2.16
└── npm@10.9.2

➜  sed -i '' 's|/Users/leo/.esvu/bin/hermes|/Users/leo/Documents/GitHub/hermes-cli-darwin-v0.12.0/hermes|g' /Users/leo/.eshost-config.json

➜  ls -l /Users/leo/.nvm/versions/node/v22.13.1/bin/eshost
lrwxr-xr-x@ 1 leo  staff  44 31 Jan 13:37 /Users/leo/.nvm/versions/node/v22.13.1/bin/eshost -> ../lib/node_modules/eshost-cli/bin/eshost.js

➜  eshost -e "42"
#### engine262
42

#### hermes

hermes: Unknown command line argument '-fenable-tdz'.  Try: '/Users/leo/Documents/GitHub/hermes-cli-darwin-v0.12.0/hermes -help'

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42


➜  curl -o /Users/leo/.nvm/versions/node/v22.13.1/lib/node_modules/eshost-cli/node_modules/eshost/lib/agents/hermes.js https://raw.githubusercontent.com/tc39/eshost/58370fcbd7183cc5b10b9bd39b7173def13f5db3/lib/agents/hermes.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3047  100  3047    0     0  13840      0 --:--:-- --:--:-- --:--:-- 13850

➜  eshost -e "42"
#### engine262
42

#### hermes
42

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42
```

approved if we want to merge this first

but latest eshost pulls in the latest hermes cli 0.13.0 (HBC bytecode ver: 96) bin

where we currently still get similar error

```console
➜  GitHub eshost -e "42"
#### engine262
42

#### hermes

hermes: Unknown command line argument '-Xenable-tdz'.  Try: '/Users/leo/.esvu/bin/hermes -help'

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42
```

i've added a more simple/minimal fix here
- https://github.com/tc39/eshost/pull/145

File: lib/agents/hermes.js [hunk 1]
```diff
@@ -32,7 +32,28 @@ class HermesAgent extends ConsoleAgent {
...
+      let stdout = '';
+      cp.stdout.on('data', str => { stdout += str; });
+      await new Promise(resolve => { cp.on('close', resolve); });
+      // https://github.com/facebook/hermes/blob/66d3f87a8fd0436634be8a1049a1db9d3aa6e9c0/lib/CompilerDriver/CompilerDriver.cpp#L2164
+      const [_, version] = /Hermes release version: (.*)/.exec(stdout);
+      if (/^0[.][0-9][.]/.test(version)) {
+        this.args.unshift('-fenable-tdz');
+      } else if (/^0[.]1[012][.]/.test(version)) {
+        this.args.unshift('-Xenable-tdz');
+      }
```
Comment (leotm) [inline lib/agents/hermes.js:51]:
```suggestion
      const [_, releaseVersion] = /Hermes release version: (.*)/.exec(stdout);
      const [__, bytecodeVersion] = /HBC bytecode version: (.*)/.exec(stdout);
      if (/^0[.][0-9][.]/.test(releaseVersion)) {
        this.args.unshift('-fenable-tdz');
      } else if (/^0[.]1[012][.]/.test(releaseVersion) && /^(9[7-9]|[1-9]\d{2,})/.test(bytecodeVersion)) {
        this.args.unshift('-Xenable-tdz');
      }
```

Comment (leotm) [reply lib/agents/hermes.js:51]: since v0.13.0 `--version` still shows 0.12.0 😄

```console
➜  hermes-cli-darwin-v0.12.0 ./hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 89

  Features:
    Zip file input
```

```console
➜  hermes-cli-darwin-v0.13.0 ./hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 96

  Features:
    Unicode RegExp Property Escapes
    Zip file input
```

Comment (leotm) [reply lib/agents/hermes.js:51]: remembering now [some time ago](https://github.com/facebook/hermes/issues/1371#issuecomment-2052065772) suggesting we show the short commit id too 😄

**Review by leotm — CHANGES_REQUESTED** [review]
one tiny quirk fix suggestion so it works testing locally

File: lib/agents/hermes.js (hunk 1 above)
Comment (gibson042) [reply lib/agents/hermes.js:51]:
```suggestion
      const [_, releaseVersion] = /Hermes release version: (.*)/.exec(stdout);
      const [__, bytecodeVersion] = /HBC bytecode version: (.*)/.exec(stdout);
      if (/^0[.][0-9][.]/.test(releaseVersion)) {
        this.args.unshift('-fenable-tdz');
      } else if (/^0[.]1[012][.]/.test(releaseVersion) && !(+bytecodeVersion >= 96)) {
        this.args.unshift('-Xenable-tdz');
      }
```

Comment (leotm) [reply lib/agents/hermes.js]: ah yes i messed up the regex, perfect ^

**Review by leotm — APPROVED** [review]
lgtm

**Comment by leotm** [comment]
does the change look good @rwaldron?
or might eshost be archived/deprecated soon?
happy to help if you need maintainers

**Comment by leotm** [comment]
was about to fork till noticed 45 branches / 40 forks
[test262-fyi/eshost](https://github.com/test262-fyi/eshost) seems next best option (or to fork from here)
- https://github.com/tc39/eshost/issues/146

**Review by ptomato — APPROVED** [review]

**Review by ryzokuken — APPROVED** [review]
